require "user.core.keymaps"
require "user.core.options"
require "user.core.plugins"

require "user.alpha"
require "user.bookmark"
require "user.colorscheme"
-- require "user.colorschemes.onedarkpro"
require "user.cmd"
require "user.lsp"
require "user.lsp.signature"
require "user.dap"
require "user.trouble"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.gitsigns"
require "user.go-vim"
require "user.scrollview"
-- require "user.dap-go"
require "user.nvim-tree"
require "user.bufferline"
require "user.close-buffers"
require "user.lualine"
--[[ require "user.autosave" ]]
require "user.toggleterm"
require "user.impatient"
require "user.possession"
require "user.markdown-preview"
require "user.project"
require "user.which-key"
require "user.git-blame"
require "user.symbols-outline"
require "user.nvim-surround"
require "user.indentline"
require "user.cheat-sheet"
require "user.lsp.dap-virtual-text"
require "user.ufo"
require "user.nvim-cmp"
