-- speed up neovim startup
vim.loader.enable()

require "core.keymaps"
require "core.options"
require "lazy-plugins"

-- require "user.bookmark"
require "colorschemes"
-- require "user.cmp"
require "lsp"
-- require "user.dap"
-- require "user.trouble"
-- require "user.telescope"
-- require "user.treesitter"
-- require "user.treesitter-context"
-- require "user.autopairs"
-- require "user.autotag"
-- require "user.comment"
-- require "user.gitsigns"
-- require "user.go-vim"
-- require "user.scrollview"
-- require "user.dap-go"
-- require "user.nvim-tree"
-- require "user.bufferline"
-- require "user.close-buffers"
-- require "user.lualine"
-- require "user.autosave"
-- require "user.toggleterm"
-- require "user.impatient"
-- require "user.possession"
-- require "user.markdown-preview"
-- require "user.project"
-- require "user.which-key"
-- require "user.git-blame"
-- require "user.symbols-outline"
-- require "user.nvim-surround"
-- require "user.indentline"
-- require "user.cheat-sheet"
-- require "user.lsp.dap-virtual-text"
-- require "user.ufo"
